### ISSUE TITLE
_imagingft.c:62:10: fatal error: 'freetype/fterrors.h' file not found

### ISSUE THREAD

**Issue by HarryWeppner** [python-pillow/Pillow#425]
Hi,

after upgrading the freetype port (using Macports) from 2.5.0_1 to 2.5.1_0 pip install fails during the build:

```
building 'PIL._imagingft' extension

/usr/bin/clang -fno-strict-aliasing -fno-common -dynamic -pipe -Os -fwrapv -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/System/Library/Frameworks/Tcl.framework/Headers -I/System/Library/Frameworks/Tk.framework/Headers -I/opt/local/include/freetype2 -IlibImaging -I/opt/local/include -I/usr/X11/include -I/Users/haraldweppner/pyenv-editing/include -I/usr/local/include -I/usr/include -I/opt/local/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c _imagingft.c -o build/temp.macosx-10.8-x86_64-2.7/_imagingft.o

_imagingft.c:62:10: fatal error: 'freetype/fterrors.h' file not found

#include <freetype/fterrors.h>

         ^
```

I presume this should `#include <freetype2/fterrors.h>` instead as `/opt/local/include/freetype2/fterrors.h` does in fact exist.

Thanks & cheerio, Harry.
