### PR TITLE
Add PyPy3.11 to CI

### PR DESCRIPTION
**Pull request by hugovk**
PyPy v7.3.18 is out:

> This release includes a python 3.11 interpreter. We are labelling it "beta" because it is the first one. In the next release we will drop 3.10 and remove the "beta" label. 

https://pypy.org/posts/2025/02/pypy-v7318-release.html

---

https://github.com/python-pillow/Pillow/pull/8757 already updated `src/thirdparty/pythoncapi_compat.h`, this is how it looked without it:

https://github.com/hugovk/Pillow/actions/runs/13203645421/job/36861505207

We also need to skip NumPy for now:

```
      [288/320] Compiling C object numpy/random/_mt19937.pypy311-pp73-darwin.so.p/meson-generated_numpy_random__mt19937.pyx.c.o
      FAILED: numpy/random/_mt19937.pypy311-pp73-darwin.so.p/meson-generated_numpy_random__mt19937.pyx.c.o
      cc -Inumpy/random/_mt19937.pypy311-pp73-darwin.so.p -Inumpy/random -I../numpy/random -I../numpy/random/src -Inumpy/_core -I../numpy/_core -Inumpy/_core/include -I../numpy/_core/include -I../numpy/_core/src/common -Inumpy -I/Users/runner/hostedtoolcache/PyPy/3.11.11/arm64/include/pypy3.11 -I/private/var/folders/s3/vj2zzxnd01l53jcjc04ljvz80000gn/T/pip-install-maut6y05/numpy_06cedbb72a3e4bbd8e8f8f77a973eb38/.mesonpy-9_4rjp9t/meson_cpu -fvisibility=hidden -fdiagnostics-color=always -DNDEBUG -Wall -Winvalid-pch -std=c11 -O3 -fno-strict-aliasing -ftrapping-math -DNPY_HAVE_CLANG_FPSTRICT -DNPY_HAVE_NEON_VFPV4 -DNPY_HAVE_NEON_FP16 -DNPY_HAVE_NEON -DNPY_HAVE_ASIMD -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE=1 -D_LARGEFILE64_SOURCE=1 -DNPY_NO_DEPRECATED_API=0 -MD -MQ numpy/random/_mt19937.pypy311-pp73-darwin.so.p/meson-generated_numpy_random__mt19937.pyx.c.o -MF numpy/random/_mt19937.pypy311-pp73-darwin.so.p/meson-generated_numpy_random__mt19937.pyx.c.o.d -o numpy/random/_mt19937.pypy311-pp73-darwin.so.p/meson-generated_numpy_random__mt19937.pyx.c.o -c numpy/random/_mt19937.pypy311-pp73-darwin.so.p/numpy/random/_mt19937.pyx.c
      numpy/random/_mt19937.pypy311-pp73-darwin.so.p/numpy/random/_mt19937.pyx.c:12442:12: fatal error: 'internal/pycore_frame.h' file not found
        #include "internal/pycore_frame.h"
                 ^~~~~~~~~~~~~~~~~~~~~~~~~
      1 error generated.
      [289/320] Compiling Cython source /private/var/folders/s3/vj2zzxnd01l53jcjc04ljvz80000gn/T/pip-install-maut6y05/numpy_06cedbb72a3e4bbd8e8f8f77a973eb38/numpy/random/_philox.pyx
      [290/320] Compiling C++ object numpy/fft/_pocketfft_umath.pypy311-pp73-darwin.so.p/_pocketfft_umath.cpp.o
      [291/320] Compiling Cython source numpy/random/_bounded_integers.pyx
      [292/320] Compiling Cython source /private/var/folders/s3/vj2zzxnd01l53jcjc04ljvz80000gn/T/pip-install-maut6y05/numpy_06cedbb72a3e4bbd8e8f8f77a973eb38/numpy/random/_common.pyx
      ninja: build stopped: subcommand failed.
```

https://github.com/hugovk/Pillow/actions/runs/13203963591/job/36862554511

---

Also fix some ShellCheck warnings in `.ci/install.sh`.

### CODE REVIEW

File: .ci/install.sh [hunk 1]
```diff
@@ -38,7 +38,10 @@ python3 -m pip install -U pytest-timeout
 python3 -m pip install pyroma
 
 if [[ $(uname) != CYGWIN* ]]; then
-    python3 -m pip install numpy
+    # NumPy doesn't support PyPy3.11
+    if [[ $GHA_PYTHON_VERSION != pypy3.11 ]]; then
+        python3 -m pip install numpy
+    fi
```
Comment (radarhere) [inline .ci/install.sh:44]: From what I see, NumPy works with PyPy 3.11 on both macOS and Ubuntu - https://github.com/radarhere/Pillow/tree/refs/heads/numpy - https://github.com/radarhere/Pillow/actions/runs/13360699763

Comment (hugovk) [reply .ci/install.sh]: Excellent, the previously-failing job passes on a re-run.

https://github.com/hugovk/Pillow/actions/runs/13203963591/job/37329242544

I've rebased the skip out :)

**Review by radarhere — APPROVED** [review]
