### ISSUE TITLE
PIL 6.1.0 Deprecations with Image.open() as im: or Image.close() doesn't work

### ISSUE THREAD

**Issue by kiflowb777** [python-pillow/Pillow#4090]
Python version: 3.6.1
PIL version: 6.1.0

After update my PIL module from 5.4.1 to 6.1.0 I replace the code according to the instructions on the page: https://pillow.readthedocs.io/en/stable/releasenotes/6.1.0.html#deprecations,
but I receive an error message.

```python
with Image.open("image.png") as img:
AttributeError: __enter__
```

```python
size = None
for index in range(image_number):
    with Image.open(image[index]) as img:
         size = img.size
```

but before:
```python
size = None
for index in range(image_number):
    img = Image.open(image[index])
    size = img.size
```
works ok.

Image.close() also dont work:
`AttributeError: module 'PIL.Image' has no attribute 'close'`

```python
>>>from PIL import __version__ as pil_version
>>>print(pil_version)
6.1.0
```

**Comment by radarhere** [comment]
Regarding `close`, I would think that you're calling it on the imported module, rather than the image instance -
```
>>> from PIL import Image
>>> Image.close()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'PIL.Image' has no attribute 'close'
>>> im = Image.new("RGB", (100, 100))
>>> im.close()
```

To see if your first problem is something similar, could you post a self-contained code example, including import statements?

**Comment by kiflowb777** [comment]
I try to fix second problem but I got:
```
>>> from PIL import Image as pil_image
>>> size = None
>>> for index in range(number_imgs):
>>>     img = pil_image.open(image[index])
 >>>    size = img.size
 >>>    img.close()
AttributeError: 'DummyPilImage' object has no attribute 'close'
```

**Comment by hugovk** [comment]
What's `DummyPilImage`?

Please include a self-contained, copy-pastable example that generates the issue if possible. Be concise with code posted.

Guidelines: https://stackoverflow.com/help/mcve

**Comment by radarhere** [comment]
`DummyPilImage` is not a part of Pillow. If you're seeing that, then you are importing something other than Pillow.

Do you have a folder called PIL in your current directory that you are importing from instead?
Alternatively, are you using https://github.com/AmbiBox/script.ambibox? Googling, that was the only DummyPilImage that I could find.

**Comment by radarhere** [comment]
Feel free to comment if you have anything further, but I'm closing this for now at least. `DummyPilImage` is not a part of Pillow, so that is a good indication that there is something else going on.
