### ISSUE TITLE
ImportError: cannot import name _imagingtk / TKINTER support not available

### ISSUE THREAD

**Issue by mike-wade** [python-pillow/Pillow#322]
I am trying to use Pillow/PIL (Currently pillow as PIL failed to find the jpeg decoder) but I cant seem get my script to work:

```
    self.photo = PIL.ImageTk.PhotoImage(self.image)
  File "/home/pi/PythonDev/env/local/lib/python2.7/site-packages/PIL/ImageTk.py", line 123, in __init__
    self.paste(image)
  File "/home/pi/PythonDev/env/local/lib/python2.7/site-packages/PIL/ImageTk.py", line 188, in paste
    from PIL import _imagingtk
ImportError: cannot import name _imagingtk
```

So I have a virtualenv setup on my raspberry pi, with presumably all of the correct packages installed:

```
--------------------------------------------------------------------
PIL SETUP SUMMARY
--------------------------------------------------------------------
version      Pillow 2.1.0
platform     linux2 2.7.3 (default, Jan 13 2013, 11:20:46)
             [GCC 4.6.3]
--------------------------------------------------------------------
*** TKINTER support not available
(Tcl/Tk 8.5 libraries needed)
--- JPEG support available
--- ZLIB (PNG/ZIP) support available
*** TIFF G3/G4 (experimental) support not available
--- FREETYPE2 support available
*** LITTLECMS support not available
*** WEBP support not available
--------------------------------------------------------------------
```

I guess if I had `TKINTER` support enabled this would work? What is that I am missing? (`Tcl/Tk 8.5` libraries come with python?)

Thanks in advance

**Comment by phillipkent** [comment]
I am using Pillow 2.7.0 and to enable TKINTER support requires newer dev libraries:

    sudo apt-get install tk8.5-dev tcl8.5-dev

**Comment by wiredfool** [comment]
The tk-dev version you need depends on what tk package your python is compiled against, so it varies by distribution.

**Comment by nolimitech** [comment]
Hi everyone,

At the start, I had this problem 

File "/usr/local/lib/python2.7/dist-packages/PIL/ImageTk.py", line 115, in __init__
    self.paste(image)
  File "/usr/local/lib/python2.7/dist-packages/PIL/ImageTk.py", line 180, in paste
    from PIL import _imagingtk
ImportError: cannot import name _imagingtk

I did 
sudo apt-get install tk8.5-dev tcl8.5-dev python-dev
sudo install python-pil python-pillow

So i installed Pillow with
sudo pip install Pillow

But it said 
Requirement already satisfied (use --upgrade to upgrade): Pillow in /usr/lib/python2.7/dist-packages
Cleaning up...

So I used the --upgrade command
Now I have the same problem.
--------------------------------------------------------------------
    PIL SETUP SUMMARY
    --------------------------------------------------------------------
    version      Pillow 2.7.0
    platform     linux2 2.7.6 (default, Mar 22 2014, 22:59:38)
                 [GCC 4.8.2]
    --------------------------------------------------------------------
    *** TKINTER support not available
    (Tcl/Tk 8.6 libraries needed)
    *** JPEG support not available
    *** OPENJPEG (JPEG2000) support not available
    --- ZLIB (PNG/ZIP) support available
    *** LIBTIFF support not available
    --- FREETYPE2 support available
    *** LITTLECMS2 support not available
    *** WEBP support not available
    *** WEBPMUX support not available
    --------------------------------------------------------------------
    To add a missing option, make sure you have the required
    library, and set the corresponding ROOT variable in the
    setup.py script.
    
    To check the build, run the selftest.py script.
    
    changing mode of build/scripts-2.7/pildriver.py from 644 to 755
    changing mode of build/scripts-2.7/pilfile.py from 644 to 755
    changing mode of build/scripts-2.7/pilfont.py from 644 to 755
    changing mode of build/scripts-2.7/pilprint.py from 644 to 755
    changing mode of build/scripts-2.7/pilconvert.py from 644 to 755
    changing mode of /usr/local/bin/pildriver.py to 755
    changing mode of /usr/local/bin/pilfile.py to 755
    changing mode of /usr/local/bin/pilfont.py to 755
    changing mode of /usr/local/bin/pilprint.py to 755
    changing mode of /usr/local/bin/pilconvert.py to 755
Successfully installed Pillow
Cleaning up...


But still nothing, so I removed the directory
rm -rf /usr/local/lib/python2.7/dist-package/PIL

And re-installed..

Still nothing. I'm using
cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.2 LTS"

Can someone help me?

**Comment by pricejt** [comment]
@nolimitech how can i do the same thing with Python3.2? I am getting the ImportError: cannot import name _imagingtk

**Comment by aclark4life** [comment]
@pricejt Make sure deps are present when you compile/install, nothing to do with Python version.

**Comment by pricejt** [comment]
How can i verify the dependencies? I installed Pillow and already had Tkinter. 
I should say i have this working fine on my Python 3.4 version on my windows machine. Trying to now get it to work on my PI which runs 3.2 python.

**Comment by aclark4life** [comment]
@pricejt What OS?

**Comment by pricejt** [comment]
@aclark4life  raspbian

**Comment by aclark4life** [comment]
OK sounds like Debian, so make sure you have Tkinter dev libraries via dpkg or apt-get or aptitude.

**Comment by pricejt** [comment]
So i ran this: sudo apt-get install tk-dev
then i tried to re-run the program and still get the same issue. Do i need to reload any of the previous libraries.

**Comment by aclark4life** [comment]
sudo apt-get install tk-dev; pip install Pillow ; retry program

**Comment by pricejt** [comment]
sorry about this. 
ok i ran sudo pip install Pillow and it gave me a compile error. 
i than ran sudo pip-3.2 install Pillow and said i already had it. 
i than ran sudo pip-3.2 install Pillow --update and it said it was up to date. 
I then re-tried program and got the same error.

**Comment by aclark4life** [comment]
No prob!  `` sudo pip-3.2 uninstall Pillow ;  sudo pip-3.2 install Pillow `` then retry. Also paste the output of the installation.

**Comment by pricejt** [comment]
you're a saint thanks for all your help. I am learning more and more each day with Python

**Comment by aclark4life** [comment]
@pricejt Great! Glad to hear :beers:

**Comment by gitaarik** [comment]
I had to add do `pip install -I --no-cache-dir Pillow` before it worked. I think pip build the cache before I installed all package requirements, and that caused it to not work event when reinstalling Pillow.

**Comment by chachi** [comment]
@gitaarik That's the ticket! Cache seems to hold onto pre-built libraries rather than rebuilding after an uninstall. Thanks!

**Comment by stacywu** [comment]
@gitaarik Thank you so much! totally made my day!!
