### ISSUE TITLE
Missing 8.0.1 .whl for pypy36 on Windows

### ISSUE THREAD

**Issue by akornatskyy** [python-pillow/Pillow#5043]
### What did you do?

On windows:

```sh
# works as expected, downloads Pillow-7.2.0-pp36-pypy36_pp73-win32.whl
pip install pillow==7.2.0

# since there is no whl, it tries to compile from source by dowloading Pillow-8.0.1.tar.gz
pip install pillow
```

### What did you expect to happen?

There is pypy36 whl for windows.

### What actually happened?

Compilation error.

### What are your OS, Python and Pillow versions?

* OS: Windows 10
* Python: pypy36
* Pillow: 8.0.1

**Comment by nulano** [comment]
Looks like there's only a PyPy3.7 wheel for the 8.0.1 release (#4764): https://pypi.org/project/Pillow/#files 

IIRC the 8.0.0 wheels for Windows omitted libpng and should not be affected by the FreeType CVE, so I think you can use 8.0.0 on Windows if you don't need CBDT font support. The two releases are identical except for the included FreeType library version in wheels.

**Comment by akornatskyy** [comment]
Yes, it works with 8.0.0.

**Comment by hugovk** [comment]
There's also only `*pypy37*` and no `*pypy36*` binaries at https://www.lfd.uci.edu/~gohlke/pythonlibs/

@cgohlke Is the general idea only to make binaries for the latest PyPy version?

**Comment by cgohlke** [comment]
I only maintain one PyPy installation on my system.

**Comment by hugovk** [comment]
Okay, thanks! Let's close this then.
