### ISSUE TITLE
Problems with installation on Win7-64, Python 2.7.12, Anaconda, PyDev, ImageTK can't be found after it worked once

### ISSUE THREAD

**Issue by Khris777** [python-pillow/Pillow#2154]
### What did you do?

1. On Win7-64, Python 2.7.12, Anaconda, using Eclipse PyDev, I imported pillow for the `ImageTK` module. Module was not found.
2. After researching on stackoverflow I uninstalled pillow (or image or PIL, honestly I can't remember exactly) with conda and installed image with pip.
3. After that my script worked, `ImageTK` could be imported.
4. Then I restarted Eclipse (I think it also did update the PYTHONPATH automatically) and everything stopped working. `ImageTK` could not be found anymore, neither could most other modules in pillow.
5. I uninstalled and reinstalled pillow countless times and in various combinations using conda and pip, also uninstalling and reinstalling image and django which was installed alongside with image. I also tried the standalone installer. I also tried using Spyder and executing my test script directly. In Eclipse I rebuilt PYTHONPATH countless times. Nothing helped.

My test script which has already worked:

	from Tkinter import *
	import PIL
    from PIL import Image

	root = Tk()
	w = Label(root,text="TitleTest").pack()
	img = PIL.ImageTk.PhotoImage(Image.open("C:\\Stuff\\Test.jpg"))
	i = Label(root,image=img).pack()
	root.mainloop()

### What did you expect to happen?

I'm expecting to be able to import `ImageTK`. In the PIL folder the file is there, `ImageTK.py` and all the other modules exist. I'm also expecting the module to consistently work and not just stop working without reason.

### What actually happened?

What I described above. I also have the following inconsistencies:

First, when in Eclipse in a new console and only importing `PIL`, I get this:

	>>import PIL
	>>dir(PIL)
	Out[6]: 
	['PILLOW_VERSION',
	 'VERSION',
	 '__builtins__',
	 '__doc__',
	 '__file__',
	 '__name__',
	 '__package__',
	 '__path__',
	 '__version__',
	 '_plugins']

This is basically an empty module. Nonetheless then I can do `from PIL import Image` and then suddenly `dir(PIL)` gives more output:

    >>from PIL import Image
	>>dir(PIL)
	Out[10]: 
	['Image',
	 'ImageMode',
	 'PILLOW_VERSION',
	 'VERSION',
	 '__builtins__',
	 '__doc__',
	 '__file__',
	 '__name__',
	 '__package__',
	 '__path__',
	 '__version__',
	 '_binary',
	 '_imaging',
	 '_plugins',
	 '_util']

Still, this is much less then what I got when I did `dir()` when I had the full functionality. There is no `ImageTK` module here and `from PIL import ImageTK` doesn't work either. It has once though, and then without proper reason it just stopped.

When I'm doing `dir(PIL)` in Spyder I'm directly getting the second output.

I'm completely lost, something broke and I have no clue what it might be.

### What versions of Pillow and Python are you using?

Python 2.7.12
Pillow 3.4.1

**Comment by wiredfool** [comment]
I'm not really sure how things are setup with your dev environment due to the number of pieces involved, but it's possible that you have more than one python environment or virtualenv, and you're installing into one and testing in another. 

So, some notes that may help, or at least give you something to look for:

1) 3.4.1 is new, and yesterday we had a bunch of time where you could have been attempting to install from source, which would generally not work so well on windows.

2) I'm not sure how conda's binaries track our package management, and how quickly they update. 

3) Generally, you should be doing things like `from PIL import Image, ImageTK` rather than importing PIL. 

4) You can check some of the features and codecs with:
```
>>> from PIL import features
>>> features.get_supported_modules()
['littlecms2', 'tkinter', 'freetype2', 'webp', 'pil']
>>> features.get_supported_codecs()
['libtiff', 'zlib', 'jpg_2000', 'jpg']
```

5) It's helpful if you can post the actual full error you're getting, rather than saying that something isn't working. Often there are clues in the exact error message that will lead to some form of enlightenment, or at least a question to ask.

**Comment by hugovk** [comment]
@Khris777 With your code I also got `AttributeError: 'module' object has no attribute 'ImageTk'`. 

Try this instead:
```python
from Tkinter import *
from PIL import Image, ImageTk

root = Tk()
w = Label(root,text="TitleTest").pack()
img = ImageTk.PhotoImage(Image.open("C:\\Stuff\\Test.jpg"))
i = Label(root,image=img).pack()
root.mainloop()
```
Note `import PIL` has been removed, `ImageTk` is imported from `PIL`, and it uses `ImageTk.PhotoImage` instead of `PIL.ImageTk.PhotoImage`.

This works on Windows 7 with Python 2.7.11 and Pillow 2.3.0 and 3.4.1.

**Comment by Khris777** [comment]
@hugovk 

I just realized the whole problem was that I used an uppercase 'K' in `ImageTk` instead of a lowercase one.

I'm simultaneously mad, embarrased, and glad.

Thanks.

That whole uppercase/lowercase stuff with TkInter I swear...

**Comment by radarhere** [comment]
At least there is a clean cut solution to your problem! So you're happy for this issue to be closed?

**Comment by Khris777** [comment]
Sure, please close it.
