### ISSUE TITLE
Pillow version from 6 to latest is not working on Django==2.1.1 on an Ubuntu server

### ISSUE THREAD

**Issue by SharmaHimanshu1991** [python-pillow/Pillow#5691]
### What did you do?
I am reading an image file on an Ubuntu 18.04 server using Django Framework (version 2.1.1)

### What did you expect to happen?
Pillow should read an image file and then processed to OCR function 

### What actually happened?
An error is got (cannot import name 'Image')
### What are your OS, Python and Pillow versions?

* OS: Ubuntu 18.04.4 LTS (GNU/Linux 5.4.0-1048-aws x86_64)
* Python: Python 3.6.9 (default, Jan 26 2021, 15:33:00)
* Pillow: from 6 to the latest version

```python
code goes here
```

**Comment by radarhere** [comment]
So Pillow works fine, until you restart? Is https://stackoverflow.com/questions/14744410/virtualenv-packages-lost-after-restart helpful?

**Comment by radarhere** [comment]
Any progress with this? I would believe that this is a problem specific to your setup.

**Comment by radarhere** [comment]
The earlier StackOverflow post suggests that maybe you are running statements like `export` on the command line, that are then lost after restart.

As this is a problem with your specific setup, it's hard to assist without further information. Specifically, a complete list of what commands are being run would be helpful. It is concerning that `pip` and `pip3` commands are being mixed with Python 2 and Python 3 - a recurring problem that we see here is people installing Pillow in a different version of Python than they are using.

**Comment by hugovk** [comment]
Yes, and please don't use `pip` or `pip3` commands directly, always use `python -m pip`, replacing `python` with whatever you use to run Python scripts.

That way you know you're installing for the same Python you're going to run.

More info here:

* https://snarky.ca/why-you-should-use-python-m-pip/

**Comment by SharmaHimanshu1991** [comment]
> The earlier StackOverflow post suggests that maybe you are running statements like `export` on the command line, that are then lost after restart.
> 
> As this is a problem with your specific setup, it's hard to assist without further information. Specifically, a complete list of what commands are being run would be helpful. It is concerning that `pip` and `pip3` commands are being mixed with Python 2 and Python 3 - a recurring problem that we see here is people installing Pillow in a different version of Python than they are using.

As this issue is occurred on Ubuntu server Django(2.1.1), now I had to update my Django env with Django (version 3.2), now Pillow is working. But on local Ubuntu Pillow is working fine with Django(2.1.1)

**Comment by SharmaHimanshu1991** [comment]
> The earlier StackOverflow post suggests that maybe you are running statements like `export` on the command line, that are then lost after restart.
> 
> As this is a problem with your specific setup, it's hard to assist without further information. Specifically, a complete list of what commands are being run would be helpful. It is concerning that `pip` and `pip3` commands are being mixed with Python 2 and Python 3 - a recurring problem that we see here is people installing Pillow in a different version of Python than they are using.

I am working on environment, so I can't use "python -m pip". Thanks for your reply.
