### ISSUE TITLE
AttributeError: 'PngImageFile' object has no attribute '_PngImageFile__frame'

### ISSUE THREAD

**Issue by parano** [python-pillow/Pillow#4509]
### What did you do?
My library BentoML is using imageio and Pillow in its tests, and with the latest release of Pillow 7.1.0 half an hour ago, I noticed some existing tests are breaking.

https://github.com/bentoml/BentoML
https://travis-ci.org/github/bentoml/BentoML/jobs/669765333?utm_medium=notification&utm_source=github_status

### What did you expect to happen?
`imageio.imread('./image.png')` should work

### What actually happened?

```
AttributeError: 'PngImageFile' object has no attribute '_PngImageFile__frame'
```
<img width="1043" alt="Screen Shot 2020-04-01 at 9 26 25 AM" src="https://user-images.githubusercontent.com/489344/78161998-18e70400-73fb-11ea-93f4-e210cd4f2636.png">

### What are your OS, Python and Pillow versions?

* OS:  mac os
* Python: 3.75
* Pillow: 7.1.0
* imageio: 2.8.0

```python
from imageio import imread
imread('./test.png')
```
It seems related to https://github.com/python-pillow/Pillow/pull/4243

**Comment by hugovk** [comment]
Git bisect says 67e3ccffeb09903e22c29d737e74070415890ed8 is the first bad commit, from #4243.

```
commit 67e3ccffeb09903e22c29d737e74070415890ed8
Date:   Sun Dec 1 12:50:21 2019 +0900

    Add APNG support

    See #3483

    Adds support for reading APNG files and seeking through frames,
    and adds basic support for writing APNG files.

 src/PIL/PngImagePlugin.py | 401 ++++++++++++++++++++++++++++++++++++++++++++--
 1 file changed, 390 insertions(+), 11 deletions(-)
```

@pmrowla Hi, please could you check this? Thank you!

**Comment by hugovk** [comment]
Ping @almarklein from https://github.com/imageio/imageio, FYI.

**Comment by hugovk** [comment]
Minimal test case, not using imageio:

```python
from PIL import Image

im = Image.open("Tests/images/hopper.png")
im.seek(0)
```

Possible fix:

```diff
diff --git a/src/PIL/PngImagePlugin.py b/src/PIL/PngImagePlugin.py
index 5bb0e2ff..afa39bc9 100644
--- a/src/PIL/PngImagePlugin.py
+++ b/src/PIL/PngImagePlugin.py
@@ -631,6 +631,7 @@ class PngImageFile(ImageFile.ImageFile):

     format = "PNG"
     format_description = "Portable network graphics"
+    __frame = 0

     def _open(self):
```

**Comment by tlambert03** [comment]
we're seeing this too in our [tests](https://cirrus-ci.com/task/5001684665499648?command=test#L800) at [napari](https://github.com/napari/napari/).

**Comment by hugovk** [comment]
Possible fix: https://github.com/python-pillow/Pillow/pull/4512.

**Comment by pmrowla** [comment]
@hugovk's change in #4512 fixes this for me. Sorry for the hassle everyone!

**Comment by SteveDoyle2** [comment]
I'm seeing this too.  I believe it's caused by PIL 7.1.0.  7.0.0 works fine.

**Comment by hugovk** [comment]
@pmrowla Thanks for checking! I've merged #4512.

Others: if you could test with master for any other regressions, that'd be appreciated.

**Comment by hugovk** [comment]
Pillow 7.1.1 has been released with a fix for this: https://github.com/python-pillow/Pillow/issues/4354#issuecomment-608020894.

Thanks all!

**Comment by tlambert03** [comment]
Thanks for the very quick fix!   just curious whether think you might end up removing 7.1.0 from pypi?  (or whether we should keep `Pillow!=7.1.0` in our requirements.txt even if pillow is just an indirect dependency)

**Comment by hugovk** [comment]
For an indirect dependency, you're probably fine removing it, especially as there was only a short time between 7.1.0 and 7.1.1.

If the problem comes up (seldom), you could ask people to upgrade. If it comes up a lot, you could pin it, or alternatively ask the dependency to add `!=7.1.0`.

**Comment by tlambert03** [comment]
can do. thanks!

**Comment by nabobalis** [comment]
Thanks for the quick bugfix release but I now get this error:

```python
../../.tox/py38-online/lib/python3.8/site-packages/sunpy/image/tests/test_transform.py:10: in <module>
    original = images.camera().astype('float')
../../.tox/py38-online/lib/python3.8/site-packages/skimage/data/__init__.py:109: in camera
    return _load("camera.png")
../../.tox/py38-online/lib/python3.8/site-packages/skimage/data/__init__.py:96: in _load
    return imread(_os.path.join(data_dir, f), plugin='pil', as_gray=as_gray)
../../.tox/py38-online/lib/python3.8/site-packages/skimage/io/_io.py:48: in imread
    img = call_plugin('imread', fname, plugin=plugin, **plugin_args)
../../.tox/py38-online/lib/python3.8/site-packages/skimage/io/manage_plugins.py:210: in call_plugin
    return func(*args, **kwargs)
../../.tox/py38-online/lib/python3.8/site-packages/skimage/io/_plugins/pil_plugin.py:36: in imread
    return pil_to_ndarray(im, dtype=dtype, img_num=img_num)
../../.tox/py38-online/lib/python3.8/site-packages/skimage/io/_plugins/pil_plugin.py:66: in pil_to_ndarray
    image.seek(i)
../../.tox/py38-online/lib/python3.8/site-packages/PIL/PngImagePlugin.py:748: in seek
    self._seek(f)
../../.tox/py38-online/lib/python3.8/site-packages/PIL/PngImagePlugin.py:791: in _seek
    cid, pos, length = self.png.read()
E   AttributeError: 'NoneType' object has no attribute 'read'
```

**Comment by hugovk** [comment]
@nabobalis I'd guess this is also a Pillow bug, there were big changes to `PngImagePlugin.py` in 7.1. Please could you report a new issue? https://github.com/python-pillow/Pillow/issues/new?template=ISSUE_REPORT.md

@pmrowla Please could you have a look at this?

Thanks!

**Comment by hugovk** [comment]
We've merged a fix (https://github.com/python-pillow/Pillow/pull/4528) for the new bug (https://github.com/python-pillow/Pillow/issues/4518). Before we release, it would be helpful if people could run their test suites with the `master` branch to check if there are other regressions. Thanks!

**Comment by tlambert03** [comment]
I can confirm for [napari](https://github.com/napari/napari) that all tests fails and issues we observed in 7.1.0 and 7.1.1 are fixed in 7.2.0.dev0. thanks!

**Comment by radarhere** [comment]
Pillow 7.1.2 has now been released with the fix for the second problem described here.
