### ISSUE TITLE
Pillow Image.save broke by lxml.etree under Python 3.6.1

### ISSUE THREAD

**Issue by Fity** [python-pillow/Pillow#3208]
### What did you do?
call `from lxml import etree` before `from PIL import Image`. Actually not sure if this is a `Pillow` issue or a `lxml` issue.

### What did you expect to happen?
`PIL.Image.save` works fine.

### What actually happened?
`PIL.Image.save` raises an IOError with message `encoder error -8 when writing image file`
full traceback:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/PIL/ImageFile.py", line 477, in _save
    fh = fp.fileno()
AttributeError: '_idat' object has no attribute 'fileno'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pillow_demo.py", line 14, in <module>
    test_pil()
  File "pillow_demo.py", line 10, in test_pil
    image.save(bytesio, 'PNG')
  File "/usr/local/lib/python3.6/site-packages/PIL/Image.py", line 1935, in save
    save_handler(self, fp, filename)
  File "/usr/local/lib/python3.6/site-packages/PIL/PngImagePlugin.py", line 822, in _save
    [("zip", (0, 0)+im.size, 0, rawmode)])
  File "/usr/local/lib/python3.6/site-packages/PIL/ImageFile.py", line 497, in _save
    raise IOError("encoder error %d when writing image file" % s)
OSError: encoder error -8 when writing image file
```

### What versions of Pillow and Python are you using?
OS: Ubuntu.
Pillow version: Both 4.1.1 and 5.1.0 can reproduce this case.
lxml version: 4.2.2(it works fine with 4.2.1)
Python: 3.6.1

Please include **code** that reproduces the issue and whenever possible, an **image** that demonstrates the issue. Please upload images to GitHub, not to third-party file hosting sites. If necessary, add the image to a zip or tar archive.

The best reproductions are self-contained scripts with minimal dependencies. If you are using a framework such as plone, Django, or buildout, try to replicate the issue just using Pillow. 

```python
import io

from lxml import etree
from PIL import Image as PILImage


def test_pil():
    bytesio = io.BytesIO()
    image = PILImage.new('RGB', (10, 10))
    image.save(bytesio, 'PNG')


if __name__ == '__main__':
    test_pil()
```

Image:

<img width="635" alt="image" src="https://user-images.githubusercontent.com/1326741/41918707-77bec2f0-798f-11e8-9cfd-f529be4f0865.png">

**Comment by Fity** [comment]
Seems not a `Pillow` issue. In `lxml` 4.2.2, it links `zlib` on [static builds](https://github.com/lxml/lxml/blob/lxml-4.2.2/CHANGES.txt#L15) and thus breaks `ZIPEncoder` in `Pillow` i think.
Not sure if `Pillow` can do anything to avoid this. Or raise a more user friendly exception.
Anyway, should be closed.

**Comment by vodik** [comment]
I just hit this issue too. Do you have any idea how to work around this at least?

**Comment by Fity** [comment]
@vodik You can downgrade lxml to 4.2.1 or import pillow before lxml.etree.

**Comment by hugovk** [comment]
Lxml 4.2.3 has been released which reverts the problem in 4.2.2 (https://github.com/lxml/lxml/pull/265#issuecomment-400768229). 

You can install lxml!=4.2.2 to make sure you don't get the problematic one (eg. https://github.com/scrapy/scrapy/issues/3308).

**Comment by YellowOnion** [comment]
I get this error, but have zero clue what module is causing it (using fbchat), how would I go about tracking down the cause of the error?

**Comment by radarhere** [comment]
Could you copy and paste full error, including traceback, that you are receiving? To be clear, you are using Pillow, yes, you're not trying to say that you're using fbchat and that this isn't a Pillow problem at all? A self-contained script to demonstrate the problem would be ideal.

**Comment by YellowOnion** [comment]
Ahh sorry, looks like my cropping values were bogus, why isn't crop throwing an exception?

having an idat exception while another exception is thrown, in save, from the use of crop is just confusing as hell.

**Comment by drscotthawley** [comment]
Hmm. It's now 2024, so downgrading doesn't seem to be an option.  What does this error mean? I'm not tiling anything. Why is there a "fileno" error?  (The device is not full) 

```python
"""
Traceback (most recent call last):
  File "/home/shawley/envs/hs/lib/python3.10/site-packages/PIL/ImageFile.py", line 536, in _save
    fh = fp.fileno()
AttributeError: '_idat' object has no attribute 'fileno'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/shawley/control-toys/scripts/process_img.py", line 137, in process_img
    img.save(filename)
  File "/home/shawley/envs/hs/lib/python3.10/site-packages/PIL/Image.py", line 2439, in save
    save_handler(self, fp, filename)
  File "/home/shawley/envs/hs/lib/python3.10/site-packages/PIL/PngImagePlugin.py", line 1402, in _save
    ImageFile._save(im, _idat(fp, chunk), [("zip", (0, 0) + im.size, 0, rawmode)])
  File "/home/shawley/envs/hs/lib/python3.10/site-packages/PIL/ImageFile.py", line 540, in _save
    _encode_tile(im, fp, tile, bufsize, None, exc)
  File "/home/shawley/envs/hs/lib/python3.10/site-packages/PIL/ImageFile.py", line 551, in _encode_tile
    encoder.setimage(im.im, extents)
SystemError: tile cannot extend outside image
```

**Comment by aclark4life** [comment]
> Hmm. It's now 2024, so downgrading doesn't seem to be an option. What does this error mean? I'm not tiling anything. Why is there a "fileno" error? (The device is not full)

Hmmm, got a test image to produce this error handy?

**Comment by drscotthawley** [comment]
Thanks for asking! Yes! But...after a little more debugging, it seems that one of the image dimensions is zero: 
```python
img.size =  (0, 128)
```
:-/  Ok. So that's what this error was telling me. I just didn't understand the message.  Not a Pillow error, just some error upstream. 
Thanks for the quick response!
