### ISSUE TITLE
Fails to build on PyPy 3.11

### ISSUE THREAD

**Issue by wRAR** [python-pillow/Pillow#8808]
```
gcc -pthread -DNDEBUG -O2 -fPIC -DHAVE_LIBJPEG -DHAVE_LIBZ -DPILLOW_VERSION=\"11.1.0\" -I/usr/include -I/usr/local/include -I/home/runner/work/scrapy/scrapy/.tox/pypy3-extra-deps/include -I/opt/hostedtoolcache/PyPy/3.11.11/x64/include/pypy3.11 -c src/encode.c -o build/temp.linux-x86_64-pypy311/src/encode.o
In file included from src/encode.c:28:
src/thirdparty/pythoncapi_compat.h:295:1: error: static declaration of ‘PyThreadState_GetInterpreter’ follows non-static declaration
  295 | PyThreadState_GetInterpreter(PyThreadState *tstate)
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /opt/hostedtoolcache/PyPy/3.11.11/x64/include/pypy3.11/Python.h:80,
                 from src/encode.c:26:
/opt/hostedtoolcache/PyPy/3.11.11/x64/include/pypy3.11/pystate.h:35:33: note: previous declaration of ‘PyThreadState_GetInterpreter’ with type ‘PyInterpreterState *(PyThreadState *)’ {aka ‘struct _is *(struct _ts *)’}
   35 | PyAPI_FUNC(PyInterpreterState*) PyThreadState_GetInterpreter(PyThreadState *tstate);
      |                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
error: command '/usr/bin/gcc' failed with exit code 1
```

**Comment by radarhere** [comment]
This has already been resolved in our main branch by #8757

Our next release is due out on April 1st.

**Comment by radarhere** [comment]
Pillow 11.2.1 has now been released.
